export type Card={r:number,s:number};
export const ranks=['','','2','3','4','5','6','7','8','9','10','J','Q','K','A'];
export const suits=['♣','♦','♥','♠'];
export function deck():Card[]{return Array.from({length:52},(_,i)=>({r:i%13+2,s:Math.floor(i/13)}));}
export function shuffle<T>(a:T[]):T[]{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
export function label(c:Card){const r=Number(c?.r),s=Number(c?.s);return (r>=2&&r<=14?ranks[r]:'?')+(s>=0&&s<4?suits[s]:'?')}
export function sortCards(cs:Card[]){return [...cs].sort((a,b)=>b.r-a.r)}
function seqValue(rs:number[]){const u=[...new Set(rs)].sort((a,b)=>a-b);if(u.length!==3)return 0;if(u.join(',')==='2,3,14')return 14;if(u[2]-u[1]===1&&u[1]-u[0]===1)return u[2];return 0;}
export function teenRank(cs:Card[]):[number,...number[]]{const a=sortCards(cs), rs=a.map(c=>c.r), counts=new Map<number,number>();rs.forEach(r=>counts.set(r,(counts.get(r)||0)+1));const vals=[...counts.entries()].sort((x,y)=>y[1]-x[1]||y[0]-x[0]);if(vals[0][1]===3)return [6,vals[0][0]];const seq=seqValue(rs);const flush=a.every(c=>c.s===a[0].s);if(seq&&flush)return [5,seq];if(seq)return [4,seq];if(flush)return [3,...rs];if(vals[0][1]===2)return [2,vals[0][0],vals.find(x=>x[1]===1)![0]];return [1,...rs];}
export const cmp=(a:number[],b:number[])=>{for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)!==(b[i]||0))return (a[i]||0)-(b[i]||0);}return 0}
export function bestFive(cs:Card[]):number[]{let best:number[]=[0];const combos=(arr:Card[],k:number,start=0,out:Card[]=[]):void=>{if(k===0){const r=evaluate5(out);if(cmp(r,best)>0)best=r;return;}for(let i=start;i<=arr.length-k;i++)combos(arr,k-1,i+1,[...out,arr[i]])};combos(cs,5);return best;}
export function evaluate5(cs:Card[]):number[]{const a=sortCards(cs),rs=a.map(c=>c.r), counts=new Map<number,number>();rs.forEach(r=>counts.set(r,(counts.get(r)||0)+1));const groups=[...counts.entries()].sort((x,y)=>y[1]-x[1]||y[0]-x[0]);const flush=a.every(c=>c.s===a[0].s);const uniq=[...new Set(rs)].sort((x,y)=>x-y);let high=uniq[uniq.length-1];if(uniq.includes(14)&&uniq.includes(2)&&uniq.includes(3)&&uniq.includes(4)&&uniq.includes(5))high=5;else if(uniq.length===5&&uniq[4]-uniq[0]===4)high=uniq[4];else high=0;if(flush&&high)return [8,high];if(groups[0][1]===4)return [7,groups[0][0],groups[1][0]];if(groups[0][1]===3&&groups[1][1]===2)return [6,groups[0][0],groups[1][0]];if(flush)return [5,...rs];if(high)return [4,high];if(groups[0][1]===3)return [3,groups[0][0],...groups.filter(x=>x[1]===1).map(x=>x[0])];if(groups[0][1]===2&&groups[1][1]===2)return [2,Math.max(groups[0][0],groups[1][0]),Math.min(groups[0][0],groups[1][0]),groups[2][0]];if(groups[0][1]===2)return [1,groups[0][0],...groups.filter(x=>x[1]===1).map(x=>x[0])];return [0,...rs];}
